repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      # Run the linter
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-Pillow~=10.2
          - types-PyYAML~=6.0
          - types-click~=7.1
          - pydantic~=2.10
          - yt-dlp~=2024.12
          - ffmpeg-python~=0.2.0
          - click~=8.1
          - pytest~=8.3
          - scikit-image~=0.24.0
          - colour-demosaicing~=0.2.0
          - scipy~=1.14
          - numpy~=2.1
        exclude: ^tests/
