repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      # Run the linter
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-Pillow
          - types-PyYAML
          - types-click
          - pydantic>=2.0.0
          - yt-dlp>=2024.0.0
          - ffmpeg-python>=0.2.0
          - click>=8.1.0
          - pytest>=8.0.0
        args: [--strict]
        exclude: ^tests/
