{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 6, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
		"classnamespace" : "box",
		"rect" : [ 100.0, 100.0, 750.0, 600.0 ],
		"description" : "RGB channel swapping in tile regions",
		"digest" : "Applies channel permutation in masked regions",
		"tags" : "jitter, GPU, channel, swap, glitch, effect",
		"boxes" : [
			{ "box" : { "id" : "obj-1", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 20.0, 500.0, 20.0 ], "text" : "sr.bandswap - RGB Channel Swapping Effect", "fontsize" : 14.0, "fontface" : 1 } },
			{ "box" : { "id" : "obj-2", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 45.0, 600.0, 40.0 ], "text" : "Swaps RGB channels in tile regions. Works with sr.tilegen for random tiles.\nperm_r/g/b: 0=R, 1=G, 2=B - controls which input channel goes to output" } },
			{ "box" : { "id" : "obj-world", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 550.0, 130.0, 120.0, 22.0 ], "text" : "jit.world sr_bandswap_ctx @visible 0" } },
			{ "box" : { "id" : "obj-3", "maxclass" : "toggle", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "int" ], "patching_rect" : [ 30.0, 100.0, 24.0, 24.0 ] } },
			{ "box" : { "id" : "obj-4", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 30.0, 130.0, 65.0, 22.0 ], "text" : "qmetro 30" } },
			{ "box" : { "id" : "obj-5", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_gl_texture", "" ], "patching_rect" : [ 30.0, 160.0, 350.0, 22.0 ], "text" : "jit.movie @autostart 1 @loop 1 @output_texture 1 @drawto sr_bandswap_ctx" } },
			{ "box" : { "id" : "obj-initworld", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 550.0, 100.0, 58.0, 22.0 ], "text" : "loadbang" } },
			{ "box" : { "id" : "obj-delay", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 400.0, 130.0, 63.0, 22.0 ], "text" : "delay 100" } },
			{ "box" : { "id" : "obj-21", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 400.0, 160.0, 120.0, 22.0 ], "text" : "read chickens.mp4" } },
			{ "box" : { "id" : "obj-6", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 560.0, 310.0, 300.0, 60.0 ], "text" : "Channel mapping:\nperm_r=2, perm_g=1, perm_b=0 = BGR swap\nperm_r=1, perm_g=0, perm_b=2 = GRB swap" } },
			{ "box" : { "id" : "obj-preset-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 400.0, 420.0, 150.0, 20.0 ], "text" : "Preset cycling button:" } },
			{ "box" : { "id" : "obj-preset-btn", "maxclass" : "button", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 400.0, 445.0, 24.0, 24.0 ] } },
			{ "box" : { "id" : "obj-preset-counter", "maxclass" : "newobj", "numinlets" : 5, "numoutlets" : 4, "outlettype" : [ "int", "", "", "int" ], "patching_rect" : [ 430.0, 447.0, 70.0, 22.0 ], "text" : "counter 0 5" } },
			{ "box" : { "id" : "obj-preset-select", "maxclass" : "newobj", "numinlets" : 7, "numoutlets" : 7, "outlettype" : [ "bang", "bang", "bang", "bang", "bang", "bang", "" ], "patching_rect" : [ 510.0, 447.0, 100.0, 22.0 ], "text" : "select 0 1 2 3 4 5" } },
			{ "box" : { "id" : "obj-preset-name", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 620.0, 447.0, 60.0, 20.0 ], "text" : "RGB" } },
			{ "box" : { "id" : "obj-p0", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 480.0, 180.0, 22.0 ], "text" : "perm_r 0, perm_g 1, perm_b 2" } },
			{ "box" : { "id" : "obj-p1", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 510.0, 180.0, 22.0 ], "text" : "perm_r 0, perm_g 2, perm_b 1" } },
			{ "box" : { "id" : "obj-p2", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 540.0, 180.0, 22.0 ], "text" : "perm_r 1, perm_g 0, perm_b 2" } },
			{ "box" : { "id" : "obj-p3", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 570.0, 180.0, 22.0 ], "text" : "perm_r 1, perm_g 2, perm_b 0" } },
			{ "box" : { "id" : "obj-p4", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 600.0, 180.0, 22.0 ], "text" : "perm_r 2, perm_g 0, perm_b 1" } },
			{ "box" : { "id" : "obj-p5", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 510.0, 630.0, 180.0, 22.0 ], "text" : "perm_r 2, perm_g 1, perm_b 0" } },
			{ "box" : { "id" : "obj-name0", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 480.0, 60.0, 22.0 ], "text" : "set RGB" } },
			{ "box" : { "id" : "obj-name1", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 510.0, 60.0, 22.0 ], "text" : "set RBG" } },
			{ "box" : { "id" : "obj-name2", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 540.0, 60.0, 22.0 ], "text" : "set GRB" } },
			{ "box" : { "id" : "obj-name3", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 570.0, 60.0, 22.0 ], "text" : "set GBR" } },
			{ "box" : { "id" : "obj-name4", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 600.0, 60.0, 22.0 ], "text" : "set BRG" } },
			{ "box" : { "id" : "obj-name5", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 700.0, 630.0, 60.0, 22.0 ], "text" : "set BGR" } },
			{ "box" : { "id" : "obj-perm-r-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 400.0, 200.0, 70.0, 20.0 ], "text" : "perm_r: 0-2" } },
			{ "box" : { "id" : "obj-dial-perm-r", "maxclass" : "dial", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 400.0, 225.0, 40.0, 40.0 ], "size" : 3.0, "min" : 0.0, "mult" : 1.0 } },
			{ "box" : { "id" : "obj-perm-r-num", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 450.0, 240.0, 50.0, 22.0 ], "minimum" : 0, "maximum" : 2 } },
			{ "box" : { "id" : "obj-prepend-perm-r", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 450.0, 270.0, 95.0, 22.0 ], "text" : "prepend perm_r" } },
			{ "box" : { "id" : "obj-perm-g-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 560.0, 200.0, 70.0, 20.0 ], "text" : "perm_g: 0-2" } },
			{ "box" : { "id" : "obj-dial-perm-g", "maxclass" : "dial", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 560.0, 225.0, 40.0, 40.0 ], "size" : 3.0, "min" : 0.0, "mult" : 1.0 } },
			{ "box" : { "id" : "obj-perm-g-num", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 610.0, 240.0, 50.0, 22.0 ], "minimum" : 0, "maximum" : 2 } },
			{ "box" : { "id" : "obj-prepend-perm-g", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 610.0, 270.0, 95.0, 22.0 ], "text" : "prepend perm_g" } },
			{ "box" : { "id" : "obj-perm-b-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 400.0, 310.0, 70.0, 20.0 ], "text" : "perm_b: 0-2" } },
			{ "box" : { "id" : "obj-dial-perm-b", "maxclass" : "dial", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 400.0, 335.0, 40.0, 40.0 ], "size" : 3.0, "min" : 0.0, "mult" : 1.0 } },
			{ "box" : { "id" : "obj-perm-b-num", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 450.0, 350.0, 50.0, 22.0 ], "minimum" : 0, "maximum" : 2 } },
			{ "box" : { "id" : "obj-prepend-perm-b", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 450.0, 380.0, 95.0, 22.0 ], "text" : "prepend perm_b" } },
			{ "box" : { "id" : "obj-7", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 2, "outlettype" : [ "jit_gl_texture", "" ], "patching_rect" : [ 30.0, 210.0, 350.0, 22.0 ], "text" : "jit.gl.pix sr_bandswap_ctx @gen sr.bandswap @perm_r 2 @perm_g 1 @perm_b 0" } },
			{ "box" : { "id" : "obj-8", "maxclass" : "jit.pwindow", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_matrix", "" ], "patching_rect" : [ 30.0, 280.0, 320.0, 180.0 ] } },
			{ "box" : { "id" : "obj-9", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 475.0, 300.0, 80.0 ], "text" : "Live noise mask on second input.\n16x16 blocks create tile regions.\nChanges every frame for chaotic glitch effect.\n\nSwap only occurs where mask > 0.5" } },
			{ "box" : { "id" : "obj-noise", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_matrix", "" ], "patching_rect" : [ 560.0, 160.0, 130.0, 22.0 ], "text" : "jit.noise 4 char 16 16" } },
			{ "box" : { "id" : "obj-thresh", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 2, "outlettype" : [ "jit_matrix", "" ], "patching_rect" : [ 560.0, 190.0, 130.0, 22.0 ], "text" : "jit.op @op > @val 128" } },
			{ "box" : { "id" : "obj-mask", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "jit_gl_texture", "" ], "patching_rect" : [ 110.0, 240.0, 180.0, 22.0 ], "text" : "jit.gl.texture sr_bandswap_ctx @name mask" } },
			{ "box" : { "id" : "obj-mask-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 700.0, 160.0, 150.0, 20.0 ], "text" : "Live noise tile mask ←" } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-initworld", 0 ], "destination" : [ "obj-world", 0 ] } },
			{ "patchline" : { "source" : [ "obj-initworld", 0 ], "destination" : [ "obj-delay", 0 ] } },
			{ "patchline" : { "source" : [ "obj-delay", 0 ], "destination" : [ "obj-21", 0 ] } },
			{ "patchline" : { "source" : [ "obj-21", 0 ], "destination" : [ "obj-5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-3", 0 ], "destination" : [ "obj-4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-4", 0 ], "destination" : [ "obj-5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-4", 0 ], "destination" : [ "obj-noise", 0 ] } },
			{ "patchline" : { "source" : [ "obj-noise", 0 ], "destination" : [ "obj-thresh", 0 ] } },
			{ "patchline" : { "source" : [ "obj-thresh", 0 ], "destination" : [ "obj-mask", 0 ] } },
			{ "patchline" : { "source" : [ "obj-mask", 0 ], "destination" : [ "obj-7", 1 ] } },
			{ "patchline" : { "source" : [ "obj-5", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-8", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-btn", 0 ], "destination" : [ "obj-preset-counter", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-counter", 0 ], "destination" : [ "obj-preset-select", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 0 ], "destination" : [ "obj-p0", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 1 ], "destination" : [ "obj-p1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 2 ], "destination" : [ "obj-p2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 3 ], "destination" : [ "obj-p3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 4 ], "destination" : [ "obj-p4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 5 ], "destination" : [ "obj-p5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 0 ], "destination" : [ "obj-name0", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 1 ], "destination" : [ "obj-name1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 2 ], "destination" : [ "obj-name2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 3 ], "destination" : [ "obj-name3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 4 ], "destination" : [ "obj-name4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-preset-select", 5 ], "destination" : [ "obj-name5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p0", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p1", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p2", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p3", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p4", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-p5", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name0", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name1", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name2", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name3", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name4", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-name5", 0 ], "destination" : [ "obj-preset-name", 0 ] } },
			{ "patchline" : { "source" : [ "obj-dial-perm-r", 0 ], "destination" : [ "obj-perm-r-num", 0 ] } },
			{ "patchline" : { "source" : [ "obj-perm-r-num", 0 ], "destination" : [ "obj-prepend-perm-r", 0 ] } },
			{ "patchline" : { "source" : [ "obj-prepend-perm-r", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-dial-perm-g", 0 ], "destination" : [ "obj-perm-g-num", 0 ] } },
			{ "patchline" : { "source" : [ "obj-perm-g-num", 0 ], "destination" : [ "obj-prepend-perm-g", 0 ] } },
			{ "patchline" : { "source" : [ "obj-prepend-perm-g", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-dial-perm-b", 0 ], "destination" : [ "obj-perm-b-num", 0 ] } },
			{ "patchline" : { "source" : [ "obj-perm-b-num", 0 ], "destination" : [ "obj-prepend-perm-b", 0 ] } },
			{ "patchline" : { "source" : [ "obj-prepend-perm-b", 0 ], "destination" : [ "obj-7", 0 ] } }
		]
	}
}
