# Tutorial 02: Early Mission Degradation
#
# GOAL: Simulate a satellite in years 1-3 of operation with minimal
# degradation - baseline cosmic ray hits and slight calibration drift.
#
# WHAT YOU'LL SEE:
# - Sparse white/black "salt & pepper" pixels from cosmic rays
# - Subtle vertical striping from detector calibration variations
# - Realistic early-mission image quality
#
# FRAMES: 45 (3 seconds at 15 fps)
# OPERATIONS: 2 (salt_pepper, corduroy)
# DIFFICULTY: Beginner
# SCENARIO: Low Earth Orbit (LEO), Years 1-3

source:
  youtube_url: "https://www.youtube.com/watch?v=MzJaP-7N9I0"

segment:
  start: 192.0    # 3 minutes 12 seconds (3m12s)
  end: 195.0      # 3 minutes 15 seconds (3m15s)
  interval: 0.0667  # 15 frames per second = 45 total frames

pipeline:
  steps:
    # Step 1: Cosmic ray hits on detector
    # Baseline rate for LEO during solar minimum
    - name: "cosmic_ray_noise"
      operation: "salt_pepper"
      params:
        # 0.01% of pixels affected (baseline LEO rate)
        amount: 0.0001

        # Equal probability salt (white) and pepper (black)
        salt_vs_pepper: 0.5

        # Reproducible results
        seed: 42

    # Step 2: Slight detector calibration drift
    # Manufacturing variations in linear array
    - name: "detector_drift"
      operation: "corduroy"
      params:
        # Subtle brightness variation (±2%)
        strength: 0.1

        # Vertical stripes (push-broom scanner)
        orientation: "vertical"

        # 30% of detector elements affected
        density: 0.3

        # Reproducible results
        seed: 100

output:
  base_dir: "./tutorials/satellite-malfunctions/02-early-mission"
  intermediate_dir: "./tutorials/satellite-malfunctions/02-early-mission/intermediate"
  final_dir: "./tutorials/satellite-malfunctions/02-early-mission/final"

# HOW TO RUN:
#   sevenrad pipeline docs/tutorials/satellite-malfunctions/02-early-mission.yaml
#
# OUTPUT:
#   ./tutorials/satellite-malfunctions/02-early-mission/final/
#     └── detector_drift_*_step01.jpg (45 images)
#
#   ./tutorials/satellite-malfunctions/02-early-mission/intermediate/
#     └── cosmic_ray_noise_*_step00.jpg (45 images showing just salt & pepper)
#
# WHAT TO LOOK FOR:
#   - Very sparse random white/black pixels (cosmic rays)
#   - Subtle vertical lines barely visible (calibration drift)
#   - Overall high image quality typical of new satellite
#
# SCIENTIFIC CONTEXT:
#   Early mission parameters based on:
#   - Landsat 8/9 OLI performance (years 0-3)
#   - Terra/Aqua MODIS baseline noise
#   - Sentinel-2 MSI early mission data quality
#
# ORBITAL ENVIRONMENT:
#   - Low Earth Orbit (600-800 km altitude)
#   - Moderate cosmic ray flux
#   - Minimal radiation damage accumulation
#   - Calibration coefficients still accurate
#
# TRY EXPERIMENTING:
#   - Increase amount to 0.0003 for solar storm conditions
#   - Adjust strength to 0.2 for more visible striping
#   - Change density to 0.5 for more affected detectors
#   - Try orientation: "horizontal" for whisk-broom scanner
