"""Constants for Max linter validation.

This module contains constant values used across the Max linter,
including known Max/MSP objects and Jitter display sinks.
"""

from __future__ import annotations

# Jitter objects that display/render images (inlet 0 expects matrix or texture)
JITTER_DISPLAY_SINKS = {"jit.pwindow", "jit.window"}

# Known Max/MSP and Jitter objects for validation
# This is not exhaustive but covers commonly used objects in this project
KNOWN_MAX_OBJECTS = {
    # Standard Max objects
    "loadbang",
    "bang",
    "button",
    "toggle",
    "message",
    "comment",
    "number",
    "flonum",
    "number~",
    "dial",
    "slider",
    "live.dial",
    "prepend",
    "append",
    "pack",
    "unpack",
    "route",
    "select",
    "gate",
    "trigger",
    "t",
    "delay",
    "pipe",
    "metro",
    "qmetro",
    "counter",
    "random",
    "drunk",
    "scale",
    "expr",
    "if",
    "coll",
    "dict",
    "send",
    "receive",
    "s",
    "r",
    "value",
    "pvar",
    "print",
    "sprintf",
    "combine",
    "regexp",
    "zl",
    # Jitter GPU objects
    "jit.world",
    "jit.gl.render",
    "jit.gl.pix",
    "jit.gl.slab",
    "jit.gl.texture",
    "jit.gl.videoplane",
    "jit.gl.node",
    "jit.gl.camera",
    "jit.gl.gridshape",
    "jit.gl.mesh",
    "jit.gl.multiple",
    "jit.gl.model",
    "jit.gl.text",
    # Jitter matrix/CPU objects
    "jit.movie",
    "jit.grab",
    "jit.record",
    "jit.vcr",
    "jit.pwindow",
    "jit.window",
    "jit.matrix",
    "jit.op",
    "jit.xfade",
    "jit.brcosa",
    "jit.scalebias",
    "jit.noise",
    "jit.gradient",
    "jit.dimmap",
    "jit.submatrix",
    "jit.concat",
    "jit.pack",
    "jit.unpack",
    "jit.iter",
    "jit.spill",
    "jit.fill",
    "jit.cellblock",
    # Utility objects
    "bpatcher",
    "thispatcher",
    "patcher",
    "p",
    "poly~",
}
